// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"google.golang.org/grpc"
	"homework_week4/internal/biz"
	"homework_week4/internal/conf"
	"homework_week4/internal/data"
	"homework_week4/internal/server"
	"homework_week4/internal/service"
)

// Injectors from wire.go:

func initServer(confServer *conf.Server, confData *conf.Data) (*grpc.Server, error) {
	dataData, err := data.NewData()
	if err != nil {
		return nil, err
	}
	userRepo := data.NewUserRepo(dataData)
	userUsecase := biz.NewUserUsecase(userRepo)
	userService := service.NewUserService(userUsecase)
	grpcServer := server.NewGRPCServer(confServer, userService)
	return grpcServer, nil
}
